# Generated by Django 5.1 on 2024-10-24 16:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('CARDS', 'Cards'), ('GOALS', 'Goals'), ('CORNERS', 'Corners'), ('WINNING_TEAM', 'Winning Team')], max_length=20)),
                ('bet_type', models.CharField(choices=[('WinOnlyBet', 'Win Only'), ('OverUnderBet', 'Over Under')])),
                ('odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('outcome', models.CharField(choices=[('WIN', 'Win'), ('LOSE', 'Lose'), ('REFUND', 'Refund'), ('IN_PROG', 'In Progress'), ('ON_HOLD', 'On Hold')], default='IN_PROG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isLive', models.BooleanField(default=False)),
                ('score', models.TextField(blank=True, default='0:0', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('FOOTBALL', 'Football'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('CRICKET', 'Cricket'), ('BASEBALL', 'Baseball'), ('HOCKEY', 'Hockey')], unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverUnderBet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bet.bet')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('direction', models.CharField(choices=[('OVER', 'Over'), ('UNDER', 'Under')], max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bet.bet',),
        ),
        migrations.CreateModel(
            name='WinOnlyBet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bet.bet')),
                ('predicted_winner', models.IntegerField(blank=True, choices=[(1, 'Home Team Win'), (0, 'Draw'), (2, 'Guest Team Win')], null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bet.bet',),
        ),
        migrations.AddField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='bet.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bet.league'),
        ),
        migrations.CreateModel(
            name='MultiBet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('total_odds', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('total_winnings', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('state', models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Pending', 'Pending')], default='Pending', null=True)),
                ('outcome', models.CharField(choices=[('WIN', 'Win'), ('LOSE', 'Lose'), ('REFUND', 'Refund'), ('IN_PROG', 'In Progress'), ('ON_HOLD', 'On Hold')], default='IN_PROG', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frozen_bet_odds', models.JSONField(default=dict)),
                ('bets', models.ManyToManyField(blank=True, null=True, related_name='multi_bets', to='bet.bet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='bet.sport'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='bet.league')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='bet.sport')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='guest_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_team_events', to='bet.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_events', to='bet.team'),
        ),
    ]
