# Generated by Django 5.1 on 2024-09-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0008_alter_bet_options_alter_overunderbet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
