# Generated by Django 5.1 on 2024-09-13 14:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0014_multibet_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multibet',
            name='bets',
            field=models.ManyToManyField(blank=True, null=True, related_name='multi_bets', to='bet.bet'),
        ),
        migrations.AlterField(
            model_name='multibet',
            name='state',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Pending', 'Pending')], default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='multibet',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='multibet',
            name='total_odds',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='multibet',
            name='total_winnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
