# Generated by Django 5.1 on 2024-09-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0017_bet_description_alter_bet_outcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='description',
        ),
    ]
