# Generated by Django 5.1 on 2024-09-07 13:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bet_type', models.CharField(choices=[('H2H', 'Head-to-Head'), ('OU', 'Over/Under'), ('PP', 'Player Performance'), ('FHW', 'First Half Winner'), ('TP', 'Total Points'), ('CS', 'Correct Score'), ('CARDS', 'Cards'), ('CORNERS', 'Corners')], max_length=10)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('outcome', models.CharField(choices=[('WIN', 'Win'), ('LOSE', 'Lose'), ('REFUND', 'Refund'), ('IN_PROG', 'In Progress')], default='IN_PROG', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadToHeadBet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bet.bet')),
                ('predicted_winner', models.IntegerField(blank=True, null=True)),
            ],
            bases=('bet.bet',),
        ),
        migrations.CreateModel(
            name='OverUnderBet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bet.bet')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('direction', models.CharField(choices=[('OVER', 'Over'), ('UNDER', 'Under')], max_length=10)),
                ('subject', models.CharField(choices=[('CARDS', 'Cards'), ('GOALS', 'Goals'), ('CORNERS', 'Corners')], max_length=10)),
            ],
            bases=('bet.bet',),
        ),
        migrations.AddField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='bet.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bet.league'),
        ),
        migrations.CreateModel(
            name='MultiBet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_odds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_winnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('outcome', models.CharField(choices=[('WIN', 'Win'), ('LOSE', 'Lose'), ('REFUND', 'Refund'), ('IN_PROG', 'In Progress')], default='IN_PROG', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bets', models.ManyToManyField(related_name='multi_bets', to='bet.bet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='bet.sport'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='bet.league')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='bet.sport')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='guest_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_team_events', to='bet.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_events', to='bet.team'),
        ),
    ]
