# Generated by Django 5.1 on 2024-09-10 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinOnlyBet',
            fields=[
                ('bet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bet.bet')),
                ('predicted_winner', models.IntegerField(blank=True, choices=[(0, 'Draw'), (1, 'Home Team Win'), (2, 'Guest Team Win')], null=True)),
            ],
            bases=('bet.bet',),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('WO', 'Win only'), ('OU', 'Over/Under'), ('PP', 'Player Performance'), ('FHW', 'First Half Winner'), ('TP', 'Total Points'), ('CS', 'Correct Score'), ('CARDS', 'Cards'), ('CORNERS', 'Corners')]),
        ),
        migrations.AlterField(
            model_name='bet',
            name='outcome',
            field=models.CharField(choices=[('WIN', 'Win'), ('LOSE', 'Lose'), ('REFUND', 'Refund'), ('IN_PROG', 'In Progress')], default='IN_PROG'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('CRICKET', 'Cricket'), ('BASEBALL', 'Baseball'), ('HOCKEY', 'Hockey')], unique=True),
        ),
        migrations.DeleteModel(
            name='HeadToHeadBet',
        ),
    ]
