# Generated by Django 5.1 on 2024-09-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_winonlybet_alter_bet_bet_type_alter_bet_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('WO', 'Win only'), ('OU', 'Over/Under')]),
        ),
    ]
