# Generated by Django 5.1 on 2024-09-10 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0007_alter_bet_options_alter_overunderbet_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='overunderbet',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='winonlybet',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='bet',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
