# Generated by Django 5.1 on 2024-09-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0010_event_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overunderbet',
            name='subject',
        ),
        migrations.AddField(
            model_name='bet',
            name='subject',
            field=models.CharField(choices=[('CARDS', 'Cards'), ('GOALS', 'Goals'), ('CORNERS', 'Corners')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
