# Generated by Django 5.1 on 2024-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0011_remove_overunderbet_subject_bet_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='subject',
            field=models.CharField(choices=[('CARDS', 'Cards'), ('GOALS', 'Goals'), ('CORNERS', 'Corners'), ('WINNING_TEAM', 'Winning Team')], max_length=20),
        ),
    ]
