# Generated by Django 5.1 on 2024-09-13 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0012_alter_bet_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='multibet',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
