# Generated by Django 5.1 on 2024-09-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0013_multibet_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='multibet',
            name='state',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('In Creation', 'In Creation')], null=True),
        ),
    ]
