# Generated by Django 5.1 on 2024-09-14 10:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0015_alter_multibet_bets_alter_multibet_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multibet',
            name='frozen_bet_odds',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='multibet',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='winonlybet',
            name='predicted_winner',
            field=models.IntegerField(blank=True, choices=[(1, 'Home Team Win'), (0, 'Draw'), (2, 'Guest Team Win')], null=True),
        ),
    ]
