# Generated by Django 5.1 on 2024-09-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0016_multibet_frozen_bet_odds_alter_multibet_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='outcome',
            field=models.CharField(choices=[('WIN', 'Win'), ('LOSE', 'Lose'), ('REFUND', 'Refund'), ('IN_PROG', 'In Progress'), ('ON_HOLD', 'On Hold')], default='IN_PROG'),
        ),
        migrations.AlterField(
            model_name='multibet',
            name='outcome',
            field=models.CharField(choices=[('WIN', 'Win'), ('LOSE', 'Lose'), ('REFUND', 'Refund'), ('IN_PROG', 'In Progress'), ('ON_HOLD', 'On Hold')], default='IN_PROG', max_length=10),
        ),
    ]
